NumPy Basics
1. Create a 1-dimensional NumPy array from a list of integers [1, 2, 3, 4, 5].
2. Create a 2-dimensional array of shape (3, 4) using np.array() with nested lists.
3. Use ndim, shape, size, and dtype to inspect the structure of an array.

In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


In [ ]:
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr_2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print("Array ndim:", arr_2d.ndim)    # Number of dimensions
print("Array shape:", arr_2d.shape)  # Dimensions (rows, cols)
print("Array size:", arr_2d.size)    # Total number of elements
print("Array dtype:", arr_2d.dtype)  # Data type of elements


Array ndim: 2
Array shape: (3, 4)
Array size: 12
Array dtype: int64


Array Creation and Initialization
1. Create a NumPy array with values from 10 to 50 using np.arange().
2. Create an array of 10 equally spaced values between 1 and 100 using np.linspace().
3. Generate a 4x4 array of random integers between 1 and 100 using np.random.randint().
4. Create a 3x3 matrix with normally distributed random numbers using np.random.randn().

In [ ]:
import numpy as np

arr = np.arange(10, 51)  # from 10 up to (but not including) 51
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
arr_linspace = np.linspace(1, 100, 10)  # 10 values including start and end
print(arr_linspace)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [ ]:
arr_randint = np.random.randint(1, 101, size=(4, 4))  # upper bound is exclusive
print(arr_randint)


[[80 14  8 65]
 [ 5 48 32 62]
 [68 61 51 57]
 [37 43 44 25]]


In [ ]:
arr_randn = np.random.randn(3, 3)  # mean=0, std=1 normal distribution
print(arr_randn)


[[-0.10096979  0.5187695   0.06943682]
 [-0.29509443 -0.84570333 -0.67579454]
 [ 1.63907601  0.91634313 -1.00183595]]


Array Reshaping and Manipulation
1. Reshape a 1D array of 12 elements into a 3x4 2D array.
2. Flatten a 2D array into a 1D array using .flatten() and .ravel().
3. Concatenate two arrays horizontally and vertically using np.concatenate() or
np.hstack()/np.vstack().
4. Transpose a 2D array and observe how rows become columns.

In [ ]:
import numpy as np
arr=np.arange(1,13)
print("\noriginal 1D array:\n",arr)


original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
reshaped=arr.reshape(3,4)
print("\n Reshaped 3x4 array:\n",reshaped)


 Reshaped 3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
flat1=reshaped.flatten()
print(flat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#using ravel
flat2=reshaped.ravel()
flat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#vertical concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

vert=np.vstack((a,b))
vert

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
horiz=np.hstack((a,b))
horiz

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
vert2=np.concatenate((a,b),axis=0)
horiz2=np.concatenate((a,b),axis=1)

In [ ]:
horiz

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
transposed=reshaped.T
transposed

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Indexing, Slicing, and Iteration
1. Access the element at the 2nd row and 3rd column of a 2D array.
2. Slice a 1D array to get elements from index 2 to 6.
3. Select all even numbers from a NumPy array using boolean indexing.
4. Replace all values in an array greater than 50 with 50.

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
# 2nd row, 3rd column → (row index 1, column index 2)
element=arr[1,2]
element

np.int64(60)

In [ ]:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_arr=arr1d[2:7]
slice_arr

array([2, 3, 4, 5, 6])

In [ ]:
arr=np.arange(1,21)
evens=arr[arr % 2==0]
evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr = np.array([10, 45, 67, 89, 23, 51, 100])
arr[arr>50]=50
print(arr)

[10 45 50 50 23 50 50]


Mathematical and Statistical Operations
1. Perform element-wise addition, subtraction, multiplication, and division between two
arrays.

2. Use np.dot() or @ operator to perform matrix multiplication.
3. Calculate the mean, median, standard deviation, and variance of a NumPy array.
4. Compute the sum and product of all elements in a 2D array.
5. Use np.cumsum() and np.cumprod() to find cumulative sum and product.
6. Apply np.where() to create a new array where values > 10 are marked as 1, else 0.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
A=np.array([[1,2],
           [3,4]])
B=np.array([[5,6],
            [7,8]])
dot_result=np.dot(A,B)
dot_result

array([[19, 22],
       [43, 50]])

In [ ]:
at_result=A @ B
at_result

array([[19, 22],
       [43, 50]])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


 Sum and Product of all elements

In [ ]:
arr2d = np.array([[1, 2],
                  [3, 4]])

print("Sum of all elements:", np.sum(arr2d))
print("Product of all elements:", np.prod(arr2d))


Sum of all elements: 10
Product of all elements: 24


Cumulative sum and product

In [ ]:
arr = np.array([1, 2, 3, 4])

print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))


Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]


np.where() condition

In [ ]:
arr=np.array([4,5,6,7,8])
new_arr=np.where(arr>10,1,0)
arr

array([4, 5, 6, 7, 8])

In [ ]:
new_arr

array([0, 0, 0, 0, 0])

Check dtype and convert to float

In [ ]:
arr = np.array([1, 2, 3, 4])
print("Original dtype:", arr.dtype)

# Convert to float
arr_float = arr.astype(float)
print("Converted dtype:", arr_float.dtype)
print("Converted array:", arr_float)

Original dtype: int64
Converted dtype: float64
Converted array: [1. 2. 3. 4.]


Convert strings to uppercase

In [ ]:
str_arr = np.array(["apple", "banana", "cherry"])
upper_arr = np.char.upper(str_arr)
print("Original:", str_arr)
print("Uppercase:", upper_arr)


Original: ['apple' 'banana' 'cherry']
Uppercase: ['APPLE' 'BANANA' 'CHERRY']


In [ ]:
arr = np.array([1, 2, np.nan, 4, np.inf])

# Check for NaN
print("NaN mask:", np.isnan(arr))

# Check for finite values (not NaN or ±inf)
print("Finite mask:", np.isfinite(arr))

# Check for numeric (useful for strings mixed with numbers)
mixed = np.array(["123", "45.6", "abc", "NaN"])
is_num = np.char.isnumeric(mixed)  # works only for digits
print("Numeric check:", is_num)


NaN mask: [False False  True False False]
Finite mask: [ True  True False  True False]
Numeric check: [ True False False False]


In [ ]:
dates = ["2025-01-01", "2025-02-15", "2025-03-10"]
date_arr=np.array(dates,dtype='datetime64')
print(date_arr)
date_arr.dtype

['2025-01-01' '2025-02-15' '2025-03-10']


dtype('<M8[D]')

Advanced Indexing and Masking
1. Use a condition mask to extract all negative values from an array.
2. Replace all values less than a threshold (e.g., 30) with 0.
3. Find the indices of all values greater than a threshold using np.where().
4. Use np.take() to extract specific elements using a list of indices.
5. Use np.unique() to extract unique elements and their counts from an array.

In [ ]:
arr = np.array([10, -5, 20, -12, 7, -3])
negatives=arr[arr<0]
negatives

array([ -5, -12,  -3])

In [ ]:
arr[arr<30]=0
arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr = np.array([10, 35, 60, 25, 80])
indices=np.where(arr>30)
indices[0]
arr[indices]

array([35, 60, 80])

np.take()

In [ ]:
arr=([100,200,300,400,500])
selected=np.take(arr,[0,2,4])
selected

array([100, 300, 500])

In [ ]:
unique_vals,counts=np.unique(arr,return_counts=True)

In [ ]:
counts

array([1, 1, 1, 1, 1])

In [ ]:
unique_vals

array([100, 200, 300, 400, 500])

Integration with Pandas (Bridge Concepts)
1. Convert a NumPy array into a Pandas DataFrame and assign column names.
2. Create a DataFrame from a 2D NumPy array and perform .mean(), .sum(), etc., on it.
3. Use .values to extract a NumPy array from a DataFrame.

In [ ]:
import pandas as pd
arr=np.array([[1,2,3],
              [3,4,5],
              [6,7,8]])
df=pd.DataFrame(arr,columns=["A","B","C"])
df

A  B  C
0  1  2  3
1  3  4  5
2  6  7  8

In [ ]:
print(df.mean())

A    3.333333
B    4.333333
C    5.333333
dtype: float64


In [ ]:
print(df.sum(axis=1))

0     6
1    12
2    21
dtype: int64


Extract NumPy array back from DataFrame

In [ ]:
arr_from_df=df.values
arr_from_df

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
type(arr_from_df)

numpy.ndarray